name: Develop 

on:
  push:
    branches:
      - develop

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        
     
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Initialize
      run: echo "Initializing..."
    
    - name: Checkout SCM
      run: echo "Initializing..."

    - name: Build
      run: echo "Building..."

    - name: Integration tests
      run: echo "Integration tests..."

    - name: Code quality
      run: echo "Code Quality..."
      
    - name: Upload artifacts
      run: echo "Upload artifacts..."
